[tool.poetry]
name = "dj-qiyu-tpl"
version = "0.3.8"
description = "Template for internal use"
homepage = "https://www.qiyutech.tech/"
authors = ["dev <dev@qiyutech.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

django = ">=3.1,<3.2"

# 第三方依赖
docutils = ">=0.16,<0.17"
pygments = ">=2.8,<3.0"

# Django QiYu Utils
django-qiyu-utils = ">=0.3.8,<0.4"

[tool.poetry.dev-dependencies]
black = ">=20.8b1"
pytest = "*"
pytest-django = "*"
pylama = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
