[tool.poetry]
name = "tikotapi"
version = "1.0.3"
description = "Documentation: tikotapi.tk or tikotapi.tutorial(). Easy API!"
authors = ["tikotstudio <tikotstudio@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
