[tool.poetry]
authors = ["Nom Nom Data Inc <info@nomnomdata.com>"]
description = "Package containing tooling for developing nominode engines"
include = ["nomnomdata/tools/engine/testpass.out", "nomnomdata/tools/engine/template/*"]
license = "LGPL-3.0-only"
name = "nomnomdata-tools-engine"
packages = [
  {include = "nomnomdata"},
]
readme = "README.md"
repository = "https://gitlab.com/nomnomdata/tools/nomnomdata-tools-engine"
version = "1.16.0"

[tool.poetry.plugins."nomnomdata.cli_plugins"]
engine-tools = "nomnomdata.tools.engine.cli:cli"

[tool.poetry.dependencies]
aiobotocore = {version = "^1.1.1", extras = ["boto3"]}
cerberus = "^1.3.2"
click-pathlib = "^2020.3.13"
docker = {version = "^4.3.1", extras = ["ssh"]}
docker-compose = "^1.26.2"
dunamai = "^1.3.0"
fsspec = "^0.8.0"
jinja2 = "^2.11.2"
nomnomdata-auth = "^2.3.4"
nomnomdata-cli = "^0.1.8"
python = "^3.7.4"
pyyaml = "^5.3.1"
requests = "^2.23.0"
s3fs = "^0.5.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
nomnomdata-engine = "^1.1.2"
pylint = "^2.6.0"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest-snapshot = "^0.4.2"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.black]
include = '\.pyi?$'
line-length = 90
target-version = ['py37', 'py38']

[tool.isort]
default_section = 'THIRDPARTY'
ensure_newline_before_comments = true
force_grid_wrap = 0
force_to_top = ['nomnomdata']
include_trailing_comma = true
known_first_party = ['nomnomdata', 'nominode', 'nomcom', 'engines_common', 'nomitall']
line_length = 90
multi_line_output = 3
use_parentheses = true

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = 90
