[tool.poetry]
name = "requests-counter"
version = "1.1.1"
description = "A tool to monitor the number of HTTP requests through an _apiKey_ in the HTTP Header."
authors = ["Alfonso Farruggia"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Arfius/requests-counter"
repository = "https://github.com/Arfius/requests-counter"
keywords = ["monitor", "api", "request", "api_key"]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
aioredis = "^1.3.1"
asyncio = "^3.4.3"
fastapi = "^0.63.0"
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"
flake8 = "^3.8.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
